# Generated by Django 5.1.7 on 2025-07-01 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_rename_created_at_blog_publish_date_blog_thumbnail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
