# Generated by Django 5.1.7 on 2025-07-01 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(max_length=5000)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(upload_to='media/blog-thumbnail')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alumni.user')),
            ],
        ),
    ]
